prod = input('Introduce el nombre del producto: ')
pre = float(input('Introduce el precio unitario: '))
ud= int(input('Introduce el número de unidades: '))
mul = float(pre*ud)
print(prod,": ", ud,"unidades x ",pre,"€"," = ",mul,"€")
